codecov:
  require_ci_to_pass: no

comment:
  behavior: new


coverage:
  status:
    project:
      # basic
      target: auto
      threshold: null
      base: auto
      # advanced
      branches: null
      if_no_uploads: error
      if_not_found: success
      if_ci_failed: error
      only_pulls: false
      flags: null
      paths: null
    patch:
      # basic
      target: auto
      threshold: null
      base: auto
      # advanced
      branches: null
      if_no_uploads: error
      if_not_found: success
      if_ci_failed: error
      only_pulls: false
      flags: null
      paths: null
